[tool.poetry]
name = "agntk"
version = "0.1.0"
description = "A toolkit for Active Galactic Nuclei (AGN) time-series analysis."
authors = ["Weixiang Yu <wy73@drexel.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.1"
celerite = "^0.4.0"
matplotlib = "^3.3.1"
toml = "^0.10.1"
scipy = "^1.5.2"
pandas = "^1.1.3"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
jupyterlab =">=2.0.0"
pytest-cov = "^2.10.1"
joblib = "^0.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
